import type { Metadata } from "next";
import { Suspense } from "react";
import { DiscoverGallery } from "@/components/marketing/discover-gallery";
import { CtaBanner } from "@/components/marketing/cta";
import { Section, SectionHeading } from "@/components/marketing/section";

export const metadata: Metadata = {
  title: "Discover",
  description:
    "Browse 3D models the SAGG3D.ai community generated. Search by prompt, orbit any model, download it or remix it in the workspace.",
};

export default function DiscoverPage() {
  return (
    <>
      <Section className="pt-16">
        <SectionHeading
          eyebrow="Discover"
          title="Generated by the community"
          description="Every model here is rebuilt live in your browser from its prompt. Open one to orbit, export or remix it."
        />
        <div className="mt-12">
          <Suspense fallback={<p className="text-sm text-muted-foreground">Loading gallery…</p>}>
            <DiscoverGallery />
          </Suspense>
        </div>
      </Section>
      <CtaBanner />
    </>
  );
}
